package diago

import (
	"context"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"os"
	"sync"
	"time"

	"github.com/emiago/diago/media"
	"github.com/emiago/diago/mediawebrtc"
	"github.com/pion/rtcp"
)

type webrtcPionSession struct {
	Laddr string
	Raddr string
	Codec media.Codec

	writer *mediawebrtc.RTPWriterTrack
	reader *mediawebrtc.RTPReaderTrack
}

func (s *webrtcPionSession) StopRTP(rw int8, dur time.Duration) error {
	t := time.Now().Add(dur)
	if rw&1 > 0 {
		return s.reader.Receiver.SetReadDeadline(t)
	}
	if rw&2 > 0 {
		// if dur == 0 {
		// 	return s.writer.sender.Stop()
		// }
		return fmt.Errorf("no support for duration based RTP write stop")
	}

	e1 := s.reader.Receiver.SetReadDeadline(t)
	// e2 := s.writer.sender.Stop()
	return e1
}
func (s *webrtcPionSession) StartRTP(rw int8) error {
	if rw&1 > 0 {
		return s.reader.Receiver.SetReadDeadline(time.Time{})
	}
	if rw&2 > 0 {
		return fmt.Errorf("no support to restart writer")
	}
	return s.reader.Receiver.SetReadDeadline(time.Time{})
}

// DialogWebrtcPion exposes media negotiated through a Pion PeerConnection.
type DialogWebrtcPion struct {
	mu      sync.Mutex
	onClose func() error
	log     *slog.Logger
	// peerConnection *webrtc.PeerConnection
	mediaSession *mediawebrtc.MediaSession

	RTPPacketWriter *media.RTPPacketWriter
	RTPPacketReader *media.RTPPacketReader

	audioReader io.Reader
	audioWriter io.Writer
}

func (d *DialogWebrtcPion) registerDialogCallbacks(c *dialogCallbacks, onMediaUpdate func(*DialogWebrtcPion)) {
	c.mu.Lock()
	defer c.mu.Unlock()

	var pendingSession *mediawebrtc.MediaSession
	c.onRemoteSDP = func(ctx context.Context, remoteSDP []byte, offered bool) error {
		d.mu.Lock()
		defer d.mu.Unlock()

		if d.mediaSession == nil {
			return fmt.Errorf("reinvite called on non initialized media")
		}

		sess := d.mediaSession
		if !offered {
			sess = d.mediaSession.Fork()
			pendingSession = sess
		}

		if err := sess.RemoteSDP(ctx, remoteSDP, offered); err != nil {
			return err
		}
		if onMediaUpdate != nil {
			onMediaUpdate(d)
		}
		return nil
	}
	c.onLocalSDP = func(ctx context.Context, answered bool, mode string, mediaSession ...*media.MediaSession) ([]byte, error) {
		d.mu.Lock()
		defer d.mu.Unlock()
		if d.mediaSession == nil {
			return nil, fmt.Errorf("reinvite called on non initialized media")
		}

		sess := d.mediaSession
		if pendingSession != nil {
			sess = pendingSession
		}
		localSDP, err := sess.LocalSDP(ctx, answered)
		if err != nil {
			return nil, err
		}
		if pendingSession != nil && answered {
			d.mediaSession = pendingSession
			pendingSession = nil
		}
		return localSDP, nil
	}
	c.onFinalize = func(ctx context.Context) error {
		return nil
	}
	c.onClose = append(c.onClose, d.Close)
}

func (d *DialogWebrtcPion) MediaSession() *mediawebrtc.MediaSession {
	return d.mediaSession
}

// OnReadRTCP sets a callback for each RTCP packet received by the WebRTC
// media session. Passing nil disables the callback.
func (d *DialogWebrtcPion) OnReadRTCP(f func(pkt rtcp.Packet, rtpStats mediawebrtc.RTPReadStats)) {
	d.mu.Lock()
	defer d.mu.Unlock()
	if d.mediaSession != nil {
		d.mediaSession.OnReadRTCP(f)
	}
}

// OnWriteRTCP sets a callback for each RTCP packet sent by the WebRTC media
// session, including reports generated by Pion. Passing nil disables it.
func (d *DialogWebrtcPion) OnWriteRTCP(f func(pkt rtcp.Packet, rtpStats mediawebrtc.RTPWriteStats)) {
	d.mu.Lock()
	defer d.mu.Unlock()
	if d.mediaSession != nil {
		d.mediaSession.OnWriteRTCP(f)
	}
}

func (d *DialogWebrtcPion) OnClose(f func() error) {
	d.mu.Lock()
	defer d.mu.Unlock()
	d.onCloseUnsafe(f)
}

func (d *DialogWebrtcPion) onCloseUnsafe(f func() error) {
	if d.onClose != nil {
		prev := d.onClose
		d.onClose = func() error {
			return errors.Join(prev(), f())
		}
		return
	}
	d.onClose = f
}

func (d *DialogWebrtcPion) Close() error {
	d.mu.Lock()
	onClose := d.onClose
	d.onClose = nil
	d.mu.Unlock()
	if onClose == nil {
		return nil
	}
	return onClose()
}

type AudioReaderWebrtcPionOption func(d *DialogWebrtcPion) error

func WithAudioReaderWebrtcPionProps(p *MediaProps) AudioReaderWebrtcPionOption {
	return func(d *DialogWebrtcPion) error {
		p.Codec = d.mediaSession.Codec()
		p.Laddr = d.mediaSession.Laddr
		p.Raddr = d.mediaSession.Raddr
		return nil
	}
}

func WithAudioReaderWebrtcPionDTMF(r *DTMFReader) AudioReaderWebrtcPionOption {
	return func(d *DialogWebrtcPion) error {
		ar := d.audioReaderUnsafe()
		r.dtmfReader = media.NewRTPDTMFReader(media.CodecTelephoneEvent8000, d.RTPPacketReader, ar)
		r.rtpDeadline = d.mediaSession
		return nil
	}
}

func (d *DialogWebrtcPion) AudioReader(opts ...AudioReaderWebrtcPionOption) (io.Reader, error) {
	d.mu.Lock()
	defer d.mu.Unlock()

	for _, o := range opts {
		if err := o(d); err != nil {
			return nil, err
		}
	}
	return d.audioReaderUnsafe(), nil
}

func (d *DialogWebrtcPion) audioReaderUnsafe() io.Reader {
	if d.audioReader != nil {
		return d.audioReader
	}

	return d.mediaSession.RTPPacketReader
}

func (d *DialogWebrtcPion) SetAudioReader(r io.Reader) {
	d.mu.Lock()
	defer d.mu.Unlock()
	d.audioReader = r
}

type AudioWriterWebrtcPionOption func(d *DialogWebrtcPion) error

func WithAudioWriterWebrtcPionProps(p *MediaProps) AudioWriterWebrtcPionOption {
	return func(d *DialogWebrtcPion) error {
		p.Codec = d.mediaSession.Codec()
		p.Laddr = d.mediaSession.Laddr
		p.Raddr = d.mediaSession.Raddr
		return nil
	}
}

func WithAudioWriterWebrtcPionDTMF(r *DTMFWriter) AudioWriterWebrtcPionOption {
	return func(m *DialogWebrtcPion) error {
		aw := m.audioWriterUnsafe()
		r.dtmfWriter = media.NewRTPDTMFWriter(media.CodecTelephoneEvent8000, m.RTPPacketWriter, aw)
		return nil
	}
}

func (d *DialogWebrtcPion) AudioWriter(opts ...AudioWriterWebrtcPionOption) (io.Writer, error) {
	d.mu.Lock()
	defer d.mu.Unlock()

	for _, o := range opts {
		if err := o(d); err != nil {
			return nil, err
		}
	}
	return d.audioWriterUnsafe(), nil
}

func (d *DialogWebrtcPion) audioWriterUnsafe() io.Writer {
	if d.audioWriter != nil {
		return d.audioWriter
	}

	return d.RTPPacketWriter
}

func (d *DialogWebrtcPion) SetAudioWriter(w io.Writer) {
	d.mu.Lock()
	defer d.mu.Unlock()
	d.audioWriter = w
}

func (m *DialogWebrtcPion) AudioReaderDTMF() (*DTMFReader, error) {
	r := &DTMFReader{}
	return r, WithAudioReaderWebrtcPionDTMF(r)(m)
}

func (m *DialogWebrtcPion) AudioWriterDTMF() (*DTMFWriter, error) {
	w := &DTMFWriter{}
	return w, WithAudioWriterWebrtcPionDTMF(w)(m)
}

func (m *DialogWebrtcPion) Echo() error {
	audioR, err := m.AudioReader()
	if err != nil {
		return err
	}

	audioW, err := m.AudioWriter()
	if err != nil {
		return err
	}

	_, err = media.Copy(audioR, audioW)
	if err != nil {
		return err
	}
	return nil
}

// PlaybackCreate creates playback for audio
func (d *DialogWebrtcPion) PlaybackCreate() (AudioPlayback, error) {
	mprops := MediaProps{}
	w := d.audioWriterProps(&mprops)
	if w == nil {
		return AudioPlayback{}, fmt.Errorf("no media setup")
	}

	if mprops.Codec.SampleRate == 0 {
		return AudioPlayback{}, fmt.Errorf("no codec defined")
	}
	p := NewAudioPlayback(w, mprops.Codec)
	// On each play it needs reset RTP timestamp
	p.onPlay = d.RTPPacketWriter.ResetTimestamp
	return p, nil
}

func (d *DialogWebrtcPion) audioWriterProps(p *MediaProps) io.Writer {
	d.mu.Lock()
	defer d.mu.Unlock()

	WithAudioWriterWebrtcPionProps(p)(d)
	return d.RTPPacketWriter
}

// AudioStereoRecordingCreate creates wav recording.
// MUST call Close for correct storing
func (d *DialogWebrtcPion) AudioStereoRecordingCreate(wawFile *os.File) (AudioStereoRecordingWav, error) {
	arProps, awProps := MediaProps{}, MediaProps{}
	ar, err := d.AudioReader(WithAudioReaderWebrtcPionProps(&arProps))
	if err != nil {
		return AudioStereoRecordingWav{}, err
	}

	aw, err := d.AudioWriter(WithAudioWriterWebrtcPionProps(&awProps))
	if err != nil {
		return AudioStereoRecordingWav{}, err
	}
	return newDialogRecordingWav(wawFile, ar, arProps, aw, awProps)
}
